# Part I: Data Preprocessing

In [2]:
import geopandas as gpd
import pandas as pd
import ee # earth engine
from shapely import wkt # for

### I. Get polygon points
1. Geojson file -> CSV file

In [ ]:
# Load the GeoJSON file
file_path = 'data/sample_geojson_file.geojson'
gdf = gpd.read_file(file_path)

# Define the output CSV file path
output_csv_path = 'data/sample.csv'

# Save the GeoDataFrame as a CSV file, excluding the index
gdf.to_csv(output_csv_path, index=False)

2. CSV file -> correct coordinates format (need to be revised)

In [ ]:
# Define a function to convert WKT to coordinates
def wkt_to_coordinates(wkt_string):
    polygon_geometry = wkt.loads(wkt_string)
    return [[coord[0], coord[1]] for coord in polygon_geometry.exterior.coords]
# Apply the function to the entire column
df['geometry_coordinates'] = df['geometry'].apply(wkt_to_coordinates)

# Drop the original WKT column if needed
df = df.drop(columns=['geometry'])
print(df)

### II. Import dataset (csv version)

1. Use the following chunk for importing processed csv file.
2. Extract the coordinates column and store as a list.

In [3]:
# Load the CSV file
csv_file_path = 'data/sample1.csv'
df = pd.read_csv(csv_file_path)
df.head()
#geometry_coordinates_list = df['geometry_coordinates'].tolist()

,OBJECTID,ParcelID,TaxYear,Address,AddrNumber,AddrPreDir,AddrStreet,AddrSuffix,AddrPosDir,AddrUntTyp,...,Shape__Length,bbox,center,minx,maxx,miny,maxy,center_x,center_y,geometry_coordinates
0,8,22 434112460329,2023,900 COBBLESTON CT,900,NaN,COBBLESTON,CT,NaN,NaN,...,507.399147,"POLYGON ((-84.322475290727 34.0775816789761, -...",POINT (-84.32219010699602 34.07777462066707),-84.322475,-84.321957,34.077582,34.078049,-84.322190,34.077775,"[[-84.3219570886809, 34.0776338049394], [-84.3..."
1,9,22 434112460337,2023,1475 SHADE TREE WAY,1475,NaN,SHADE TREE,WAY,NaN,NaN,...,489.575744,"POLYGON ((-84.3227236937518 34.0777773676702, ...",POINT (-84.32247060207402 34.07799112942287),-84.322724,-84.322129,34.077777,34.078197,-84.322471,34.077991,"[[-84.3226054945046, 34.0781970511354], [-84.3..."
2,10,22 434112460345,2023,1485 SHADE TREE WAY,1485,NaN,SHADE TREE,WAY,NaN,NaN,...,513.390873,"POLYGON ((-84.3226054945046 34.0780105586958, ...",POINT (-84.32231815150169 34.0782224749837),-84.322605,-84.322001,34.078011,34.078478,-84.322318,34.078222,"[[-84.3220014548172, 34.0780968612044], [-84.3..."
3,11,22 434112460352,2023,1495 SHADE TREE WAY,1495,NaN,SHADE TREE,WAY,NaN,NaN,...,537.054112,"POLYGON ((-84.3223954997853 34.0780968612044, ...",POINT (-84.32209405245058 34.078390528987725),-84.322395,-84.321921,34.078097,34.078594,-84.322094,34.078391,"[[-84.3219206693014, 34.0785940157614], [-84.3..."
4,12,22 434112460436,2023,1530 SHADE TREE WAY,1530,NaN,SHADE TREE,WAY,NaN,NaN,...,556.900499,"POLYGON ((-84.3222440183064 34.0787476414142, ...",POINT (-84.3220382407139 34.079005623443344),-84.322244,-84.321860,34.078748,34.079234,-84.322038,34.079006,"[[-84.3218599160399, 34.0792335134603], [-84.3..."